### PR TITLE
v2.0.0

### PR DESCRIPTION
**Pull request by jmtd**
This PR is essentially a no-op but introduces a commit (HEAD^) which we can later tag with 2.0.0.

### CODE REVIEW

**Comment by goldmann** [comment]
Such big changes and bump micro version only? https://github.com/jboss-dockerfiles/dogen/compare/1.5.2...master

-1 from me.

**Comment by goldmann** [comment]
In fact that's why I did not released it yet - I wanted to have 2.0.0 version ready.

**Comment by jmtd** [comment]
OK, is there anything else you want in 2.0.0.? I wanted a version to target for the XPaas images, I have a PR that works with current master (no need for additional patches)

**Comment by jmtd** [comment]
OK here's a food-for-thought with 2.0.0 instead.

**Comment by goldmann** [comment]
The question is - are current features complete to be called 2.0.0? Do we want to add/modify/remove some features? Why not to release a RC version instead first?

**Comment by l-d-j** [comment]
i think it doesn't matter much. If there was a big enough change for 2.0 its ok to bump and then release 2.1 with additional features.

**Comment by goldmann** [comment]
I think it does - we need to start maintain a bit of quality with our releases :) This includes code itself, documentation or lack of it and versioning.

**Comment by jmtd** [comment]
An RC is a good idea. There are other things we might want to change. I just want *any* version to reference from the openshift jboss-dockerfiles :)

**Comment by jmtd** [comment]
Sorry for the noise, but since we're not talking about v1.5.3 anymore I'll rename the merge branch (or it will look weird), so need a new PR.

**Pull request closed without merging**
