### PR TITLE
rename the 'hash' key to 'md5sum'

### LINKED ISSUE #13: "hash" key should be renamed to md5sum
The "hash" key is used to verify downloaded files. The code actually calculates an MD5 hash sum, I think the key should indicate this.

We could/should also consider using a stronger hashing algorithm, or support multiple keys (md5sum/sha256sum/etc.)

### PR DESCRIPTION
**Pull request by jmtd**
Closes #13.

### CODE REVIEW

**Comment by goldmann** [comment]
So, the outcome of the discussion is to make it explicit to use `md5sum` key and not to make it general and make it part of the value like: `md5sum:abcdabcdabcd`? I can live with it, but this would prevent us in the future to change the hash algorithm without breaking already existing yaml's. Not sure if we are going to support backwards-compatibility. We probably should.

**Comment by jmtd** [comment]
I'm not sure if we reached consensus, but the four possible approaches are

1. As currently: a generic key, no explicit algorithm defined. Problem: if we change algorithm, existing hashes will be invalid. Also it would be nice to be explicit about algorithm.

2. rename to md5sum. Problem: if we want to use a different hash algorithm in future, existing YAML will break.

3. define generic key with specific algorithm encoded in the value. e.g.

  - chksum: md5:ab256343...

Problem: YAML file is no longer *just* YAML, you need to decode the string in some way, so we're defining another meta language, need validation/tests etc. for parsing the value out of the string.

4. define generic key with specific algorithm as a sub-key. e.g.

  - chksum: { algorithm: md5, value: ab256343... }

This is my preferred solution. Schema does not define/constrain the values, so we can introduce new algorithms without breaking existing YAMLs (although we would break existing YAMLs *now* by migrating to a different schema like this one...). File remains pure YAML so no need to write parser/tests/validation for value as per 3.

**Comment by jmtd** [comment]
oh I just realised I wrote pretty much the same comment already in #13, sorry for the noise!

**Comment by goldmann** [comment]
I think second option could work too, we just need to find what keys are there and find them in order of preference, for example if sha1 is now preferred, try to find `sha1sum` key -- if found - great, if not, try to find `md5sum` key.

**Comment by jmtd** [comment]
option 3 reminds me of magnet https://en.wikipedia.org/wiki/Magnet_URI_scheme

**Pull request merged**
