### PR TITLE
Add support for file:// URLs

### PR DESCRIPTION
**Pull request by lulf**
This would allow the yaml files to specify local files, which is nice if you want to co-locate your image.yaml with the build artifacts.

### CODE REVIEW

**Comment by lulf** [comment]
Some tests that mock the requests.get seem to fail since it first creates a session to mount the FileAdapter.  I'm not sure to fix this as i've never used this mocking framework.

**Comment by lulf** [comment]
Also noticed that it has to be an absolute path, so perhaps a different approach using 'file' instead of 'url' and handle it in dogen explicitly would be better.

**Comment by goldmann** [comment]
This could be written as a plugin. Example idea: when an `artifacts` directory found next to the `image.yaml` is found - all files inside this directory are copied into target directory. Dogen finds these files and uses them to build the image.

**Comment by lulf** [comment]
+1 That sounds like a better approach . Ideally the artifacts dir  should be configurable

**Comment by goldmann** [comment]
Sure, makes sense. There would be two options:

1. To enable this plugin (plugin would be disabled by default)
2. To  change the path to the artifact directory

**Comment by goldmann** [comment]
I'll close this PR, @vbusch volunteered to open a new PR with updated logic.

**Pull request closed without merging**
