### PR TITLE
Switch from fedora to alpine linux to have much smaller image

### PR DESCRIPTION
**Pull request by goldmann**

### CODE REVIEW

**Comment by jmtd** [comment]
Build output warns that it could not compile libYAML, so python implementation is used instead. Is that OK/expected?

First attempt to run this resulted in

```
/launch.sh: line 11: syntax error: unexpected "("
```

But it might be an issue with the image I'm trying to build.

**Comment by jmtd** [comment]
need bash apkg + change hashbang to /bin/bash, also 

```
/launch.sh: line 14: groupadd: command not found
```

**Comment by goldmann** [comment]
PR rebased and updated.

**Comment by goldmann** [comment]
Difference in size: `340.6 MB` vs `67.84 MB`.

**Pull request merged**
